sudo: false
env:
  global:
    # VPS_PASSWORD
    - secure: "OC4h7k5TI+niCAv9J8BmbMFRssm6DVc23wPkNXfEDzZ8/Etm5R8A/nuzqpmMW/x75v6OabEkyVKmflGpj0tKJ6d+Wx7o1bNUvd/G1PwTxRfqVtRVgWszi+NzFXAPletrSkRDWrCd9NB6juCXQoHrEKpSk2DksrjShhOXR6TeXqIXbt4zWqqZ193/4S0JRgUZ5aabsJ9Lv3YPnZQ6R74Mj7H2O+Gle7iHRvGAhy9E3voTtRuYwmX0L9CHLrme3iNrtJr/Tsz9G3PhRpP6Tn/Lig0S70HZPICAW0vG3AFfn1OC2MPb2hs5MrzKEUNE510ZD2XNtOceybSva9yWDlqslWIkJj1ro5j89+X6x61l8evyPUw8pDpzXvYZIkbovE6raSuQzb2+i6RTTjLQAUKcFHeimrypmj4BUMRGs94lHiLwJ2Ap8lL+I8ZcV64DLooGCorwz9QVL5H+N1lL0o+Ij0pTQJGJrdRXddrTCBBHGTxrQaM85WqTWsqh8+xGfFQbeEOythCSPyz+R+46H/zrAMxZ8pLl0S6SQjapKXNdZULUz0Jg/l3zsBDTE1dCcFuoGPl6snYPgI6A/4F85yMoB2jwelfSCA8LXQcLQLI84MzYLA6QBF4mi7PAeFtBH62ip7er39hiYIV+xHDueYHiUD7FQlnuEWmhJ51m/2kiAZQ="
    # VPS_LOGIN
    - secure: "0/kRgNewEq46HiwVHlShdJZdUK/+CJEWkh3TFWrtYssPvwTGvdq6EZ8WAhyGsgimYjsFNrZ/OOeXajHjxfQw4loz4YkGF5e69NcqOfwmp7AOK3yqCFN4Lb8XqHLLOj7J74A8icJt0EMrH9tuSLMgziV1ITq19OQXZQCkinVTuIp4T9iiuephJKcNv4WYhcXwejBq3Nv/wIXCplaFZRw7ZvIyJd9pL+fPSXUipOU+321awcyy0T/QDCNJGUKe8i1z3tp2qDEwEvq9v0ZvOzHuZUfvbctZcEswK2Zyq0ck8ctYyVAuzCkhLmfPxqWBmaHyQvVo0Uzvsa9e8NqjLhuBtf3ll8J9ADsqZJURuMDSTpP+5RAzm2igbARsQ/damarB5ckq5AGAFZ2gB7aJZdJVlq7FYfip+hIN94xOXpOijCMNlMWKztq8eqQ5Hc7UhxXRXGYWWQa4cadlY33ouOx/Wi24ZhVUBb2PPgccSxk1QWzXzLsYc+2WfIM9qp/fMXnvPYEnl7dM8AJfqcDNb1cMs+D20pxDxNueDf5a1ajsHNZxER8JpLJjFFsEvUQhmxhEwUseVD29FU3mF3g6RCMc7xJz6Hl6obwYag6960JxQfeC5nbSaPJDf2p7h9kB0Ng25OEMhhAd96sWfNkjAhE6/f2N+KIsbr9bdL5Cn5SjCQU="
    # VPS_HOST
    - secure: "uA4CjNPh+Sj2xL3rTt7bFIKVC+NPbzCZ+LBFOoUrgM8HQYW8cxoVxvIivJJgMoJMl2c43XdNhynKHkFNgdzWul8ytunHlb7UbYIfVacJ6WEW/+vMDh+7k7D5ApiHusOXOjkq8uNwHLeFFWPpx817wrFMSmiD+OneckuKh0n7CH5j5oy4qV/VfBWM1JPk1dAr4I/IG8Je6JYkL0A/E2dSItVe026UX4466vwiqH6ULnHJkXjzUqEOi4gbh9r5AKMm/OnGfffdli7W1akIPWF3HehL6Ns2aftpp2kWzhPnXke53KDECHOM+fAhCuNK+v33k2CHiAJdQCNSD5aAPfZC0pVoAw6rFEvTQfUYkZymLZYIXYXqqA+NSDzJ9ExcMUNyd177jAKQMz3RoNskd+CyuuioMoyqiG5n7rI3GYCMRl9pvM4lPjKqxFbv0pY5wpdxDhkfNc2ACpnFOsZHZf/LRH2RrwBix06FuOKaXVvrpd8KW/hu3hMxa4bYED22Fv+mn6nfAcaIdX8mvyZ50NbHvhjcxHn+DcbocpA8J1xDMKYYwn7zrROSWeyBMeo7TeStHdOzGKNLmsQmebkbNnx58UeMCGG7ZIHGfXpQxo5sAXZwhCe6QmHoU2U5RigzY1ZRWpihsJUh+4pQrtVVz3pSbBs/nhiwoPMdl9kuxM1LVq8="
branches:
  only:
   - master
addons:
  apt:
    packages:
      - sshpass
  
language: java
jdk: oraclejdk7
install: mvn install -DskipTests=true
after_success:
  - sshpass -p $VPS_PASSWORD scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no target/ocelot-qunit-ear/ocelot-qunit-ear*.ear $VPS_LOGIN@$VPS_HOST:/root/autodeploy/ocelot-qunit-ear.ear
